<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Outras aes</name>
   <tag></tag>
   <elementGuidId>2bf54a39-ec65-426f-9989-8c5628695169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='button-dropup'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Outras ações&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ed24b8f-71cd-450f-b033-ac4fc4f4531c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-dropup</value>
      <webElementGuid>070e5338-a44e-4a7f-a0a9-da98ae703b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7143df7c-513f-4b15-a1b4-574477fbcac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-dropdown</value>
      <webElementGuid>4dbc15a8-2d52-404a-bc38-efb8215d0fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary dropdown-toggle</value>
      <webElementGuid>4d6ead0a-30dd-4919-b852-c12024ea1cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c3acc72-539c-402d-8dba-cdd48985b69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69bd55cb-66d5-4bf2-b6ef-e46e59a9ff18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Outras ações 
              </value>
      <webElementGuid>98e91836-4436-40e3-9389-0a39eaca4472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-device-desktop dx-device-generic ng-tns-0-0&quot;]/app-root[@class=&quot;layout-fixed&quot;]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/section[@class=&quot;section-container&quot;]/div[@class=&quot;content-wrapper ng-star-inserted&quot;]/sittax-apuracao[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row mb-3 ng-star-inserted&quot;]/div[@class=&quot;col-12 perfil&quot;]/div[@class=&quot;card w-100 m-0&quot;]/div[@class=&quot;card-body max-width-info d-flex&quot;]/div[@class=&quot;w-50 d-flex justify-content-between content-actions align-items-center ng-star-inserted&quot;]/div[@class=&quot;actions&quot;]/div[@class=&quot;btn-group p-2&quot;]/button[@id=&quot;button-dropup&quot;]</value>
      <webElementGuid>9b8d575e-7346-4958-8f6b-3067c2c83bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='button-dropup'])[2]</value>
      <webElementGuid>3f9a02d5-ed65-4466-b7c8-6924d479b595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ações'])[1]/following::button[1]</value>
      <webElementGuid>d3e4c55a-c709-405a-ae87-ccf97a6f7e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BETA'])[1]/following::button[2]</value>
      <webElementGuid>6302e6d3-6c30-4f84-b58d-c1fc5c09bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geral'])[1]/preceding::button[1]</value>
      <webElementGuid>39137516-2c35-47f7-a3ad-44e6f93182e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anexo I'])[1]/preceding::button[1]</value>
      <webElementGuid>a45c3b53-33bb-4345-976f-3189fd317ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outras ações']/parent::*</value>
      <webElementGuid>e9eae961-09ad-45b5-b133-3e1e98c8aaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ffa1df7c-d9ef-49ae-8be9-e202743e09e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-dropup' and @type = 'button' and (text() = '
                Outras ações 
              ' or . = '
                Outras ações 
              ')]</value>
      <webElementGuid>cddc26ab-35b3-4621-9c08-f795b617a60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
