<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mar2025</name>
   <tag></tag>
   <elementGuidId>543ec8aa-ea0a-4693-8518-2af577f668ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='periodoFiscal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#periodoFiscal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;mar/2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12dfb451-4249-490b-898d-4db91fd15940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>852f9502-1aae-449b-bc01-5f010062ac4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>periodoFiscal</value>
      <webElementGuid>2f8907e3-dae3-4f06-8cd6-fd575b121a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>periodoFiscal</value>
      <webElementGuid>059f9a12-69d6-4a80-8693-3b9165c10cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>65756624-95c5-4ca5-b732-69bc29906402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a33f40aa-7ab4-4281-a35c-a6cd0da53a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b383a2d-90da-40f1-82e2-6a402a14aec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Selecionar Período</value>
      <webElementGuid>158df6cc-9d0d-40c6-a52d-0fcee73e40e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Selecione um período abaixo</value>
      <webElementGuid>74fe6711-932e-4444-8273-21506b4b1ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sittaxPeriodo</value>
      <webElementGuid>432720d8-7e91-4ebd-a153-19b3246a0718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        mar/2025
      </value>
      <webElementGuid>5ae81dcc-351b-4443-b568-975a080ca92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;periodoFiscal&quot;)</value>
      <webElementGuid>07cf7c7e-79d8-4e1f-8ccf-345a17cda46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='periodoFiscal']</value>
      <webElementGuid>1e648a0f-4de3-45bf-9e7d-032a3b39a1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione uma empresa'])[1]/following::div[3]</value>
      <webElementGuid>566dc5b9-b69b-404b-b839-0bd1dd22889d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione um escritório'])[1]/following::div[8]</value>
      <webElementGuid>c347cbd7-b9fb-4c4e-aef9-64c5f76e38f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[3]</value>
      <webElementGuid>2217257b-c6e3-49ed-9219-68c5b7e9992e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dados do Escritório'])[1]/preceding::div[10]</value>
      <webElementGuid>593a0f51-5f9c-4bc8-891a-c1f00cd47139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mar/2025']/parent::*</value>
      <webElementGuid>a48ec7c6-6dbf-413d-a41a-6fd4bb0c4922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div</value>
      <webElementGuid>cca138c4-2b00-4458-b5f4-9e015ff354dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'text' and @id = 'periodoFiscal' and @name = 'periodoFiscal' and @placeholder = 'Selecionar Período' and @title = 'Selecione um período abaixo' and (text() = '
        mar/2025
      ' or . = '
        mar/2025
      ')]</value>
      <webElementGuid>6e32cdbe-d87b-4a37-8fa1-a1977cbcecb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
