<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selecione uma empresa</name>
   <tag></tag>
   <elementGuidId>c3b3deb5-5976-46f3-9b50-3f0ab18ecbc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='selectHeaderEmpresas']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectHeaderEmpresas > div.ng-select-container > div.ng-value-container > div.ng-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Selecione uma empresa&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>584b9257-cde7-4b47-b3e6-dab21882af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-placeholder</value>
      <webElementGuid>cc52c607-dfe6-484b-9e51-108e32024358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecione uma empresa</value>
      <webElementGuid>c08538f0-9639-4fba-8eb7-05e1a2226684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectHeaderEmpresas&quot;)/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-placeholder&quot;]</value>
      <webElementGuid>ffd1703c-a036-4c8c-8bf8-02ebdaa63aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='selectHeaderEmpresas']/div/div/div</value>
      <webElementGuid>d49af912-e364-4616-afb4-8207b7de6185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione um escritório'])[1]/following::div[5]</value>
      <webElementGuid>3b6464a6-af32-4210-80d4-7211bfcbf8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desenvolvedor'])[1]/following::div[14]</value>
      <webElementGuid>1b182348-ed61-40dd-8dca-ce1777c49359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mar/2025'])[1]/preceding::div[28]</value>
      <webElementGuid>809772c8-78cf-44d2-8c80-35a07901bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selecione uma empresa']/parent::*</value>
      <webElementGuid>48a62463-5bd6-4fdb-a99b-843648d31bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ng-select/div/div/div</value>
      <webElementGuid>1fe17958-e6e9-496b-8f96-3b28c62d5710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selecione uma empresa' or . = 'Selecione uma empresa')]</value>
      <webElementGuid>9ebe4224-8820-4ccd-9388-c747f166c81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
