<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fechar_p-0 rounded-circle (1)</name>
   <tag></tag>
   <elementGuidId>07e0ff27-68ee-4312-a8fc-303346b2142f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.p-0.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Avatar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ffb030a6-db22-44d1-aa99-79101b151cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>e54757ae-aa5c-48a1-b3df-7522c8ac059c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 rounded-circle</value>
      <webElementGuid>883eb9fb-0ad8-4350-bec1-c491861727d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/perfil.svg</value>
      <webElementGuid>d45e38a2-b763-4837-a165-532cc3832d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-device-desktop dx-device-generic ng-tns-0-0&quot;]/app-root[@class=&quot;layout-fixed aside-collapsed&quot;]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/app-header[@class=&quot;topnavbar-wrapper&quot;]/nav[@class=&quot;navbar topnavbar&quot;]/div[@class=&quot;navbar-header d-flex align-items-center&quot;]/app-userblock[1]/div[@class=&quot;item user-block ng-star-inserted&quot;]/div[@class=&quot;user-block-picture&quot;]/div[@class=&quot;user-block-status&quot;]/img[@class=&quot;p-0 rounded-circle&quot;]</value>
      <webElementGuid>5ab942a2-cd19-4a14-9ebf-5b85a775eac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Avatar']</value>
      <webElementGuid>6b429481-4c1a-4de5-bb80-5efe27d91c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>255de80b-0c14-455b-a989-123742deffab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Avatar' and @src = 'assets/img/perfil.svg']</value>
      <webElementGuid>76cb874b-6442-4815-9720-fe110d024a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
