<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fechar_p-0 rounded-circle (2)</name>
   <tag></tag>
   <elementGuidId>bfa4dc7e-ff74-4223-83fa-a3a38759011a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.p-0.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Avatar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12ad071f-0ab2-4d4d-8303-0ad851a688f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>d97015a0-3414-4145-96ea-2abcf08b874f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 rounded-circle</value>
      <webElementGuid>a1fd0226-9ba5-4115-a55c-56a7534f191e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/perfil.svg</value>
      <webElementGuid>5f39c902-1071-4f14-a7b8-72188692d666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-device-desktop dx-device-generic ng-tns-0-0&quot;]/app-root[@class=&quot;layout-fixed aside-collapsed&quot;]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/app-header[@class=&quot;topnavbar-wrapper&quot;]/nav[@class=&quot;navbar topnavbar&quot;]/div[@class=&quot;navbar-header d-flex align-items-center&quot;]/app-userblock[1]/div[@class=&quot;item user-block ng-star-inserted&quot;]/div[@class=&quot;user-block-picture&quot;]/div[@class=&quot;user-block-status&quot;]/img[@class=&quot;p-0 rounded-circle&quot;]</value>
      <webElementGuid>78b6794f-6473-46fb-a264-080585b898b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Avatar']</value>
      <webElementGuid>a9db41c1-99f6-4189-9310-c33ab3fe9b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c30a647e-4d8d-40cd-8015-19d205a919b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Avatar' and @src = 'assets/img/perfil.svg']</value>
      <webElementGuid>5a7af984-bd8d-4c9a-b0f3-6570e6b0c750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
