<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fechar_p-0 rounded-circle</name>
   <tag></tag>
   <elementGuidId>27c3f60e-0285-433f-bcfe-6ce4417f642f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.p-0.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Avatar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36a7f351-c251-40d5-b49e-21cfe9d05af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>22ad2ad3-cf6d-4900-a117-fedf3ffc1bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 rounded-circle</value>
      <webElementGuid>67773d0d-1963-4b7e-81b4-a9fc49dc7f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/perfil.svg</value>
      <webElementGuid>08ec2996-eea9-4056-b41a-f7117facc4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-device-desktop dx-device-generic ng-tns-0-1&quot;]/app-root[@class=&quot;layout-fixed aside-collapsed&quot;]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/app-header[@class=&quot;topnavbar-wrapper&quot;]/nav[@class=&quot;navbar topnavbar&quot;]/div[@class=&quot;navbar-header d-flex align-items-center&quot;]/app-userblock[1]/div[@class=&quot;item user-block ng-star-inserted&quot;]/div[@class=&quot;user-block-picture&quot;]/div[@class=&quot;user-block-status&quot;]/img[@class=&quot;p-0 rounded-circle&quot;]</value>
      <webElementGuid>21d42c45-db65-424a-aa40-4dc8a8f6bcf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Avatar']</value>
      <webElementGuid>0ae1d3ea-4a97-48bc-bed9-93e795a2ab62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f06d8616-e27e-4c56-9936-bbe42ec14f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Avatar' and @src = 'assets/img/perfil.svg']</value>
      <webElementGuid>f0df0d4e-7f62-48c8-9d90-3f3dab1d4439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
